In [6]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load (Remember to Change These)
precip_data_to_convert = Path("Data/Clean_county_avg_precipitation.csv")
temp_data_to_convert = Path("Data/Clean_county_avg_temperature.csv")
LD_data_to_convert = Path("Data/Clean_Ld-Case-Counts-by-County-01-20.csv")
WN_data_to_convert = Path("Data/Clean_WestNile-Case-Counts-by-County-01-20.csv")

# Read Data File and store into Pandas DataFrames
precip_data_ = pd.read_csv(precip_data_to_convert)
temp_data_ = pd.read_csv(temp_data_to_convert)
LD_data_ = pd.read_csv(LD_data_to_convert)
WN_data_ = pd.read_csv(WN_data_to_convert)

precip_data_.head()

,Unnamed: 0,county,state,2001,2002,2003,2004,2005,2006,2007,...,2015,2016,2017,2018,2019,2020,2021,lat,lon,FIPS
0,0,Abbeville County,SC,8.08,12.05,14.74,18.80,9.30,10.48,6.63,...,13.90,9.06,8.95,13.85,6.20,16.01,13.85,34.213809,-82.460460,45001
1,1,Acadia Parish,LA,20.78,16.82,15.17,7.72,17.58,15.16,19.85,...,11.43,29.17,18.34,21.57,17.39,18.01,21.91,30.291497,-92.411037,22001
2,2,Accomack County,VA,11.22,8.96,16.00,23.94,9.45,18.56,7.26,...,11.20,18.21,18.05,15.20,10.80,16.19,13.39,37.765944,-75.757807,51001
3,3,Ada County,ID,0.74,0.43,0.96,1.27,0.32,0.36,1.08,...,1.37,0.81,0.86,0.08,1.08,0.16,1.54,43.447861,-116.244456,16001
4,4,Adair County,IA,9.13,9.49,6.81,12.17,7.76,15.41,17.27,...,18.94,19.61,10.04,16.50,14.38,6.44,9.74,41.328528,-94.478164,19001

In [7]:
# Drop the first column from precip_data_
precip_data_.drop(columns=['Unnamed: 0'], inplace=True)

# Drop the first column from temp_data_
temp_data_.drop(columns=['Unnamed: 0'], inplace=True)

# Drop the first column from LD_data_
LD_data_.drop(columns=['Unnamed: 0'], inplace=True)

# Drop the first column from WN_data_
WN_data_.drop(columns=['Unnamed: 0'], inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [8]:
precip_data_.head()

,county,state,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,2021,lat,lon,FIPS
0,Abbeville County,SC,8.08,12.05,14.74,18.80,9.30,10.48,6.63,9.72,...,13.90,9.06,8.95,13.85,6.20,16.01,13.85,34.213809,-82.460460,45001
1,Acadia Parish,LA,20.78,16.82,15.17,7.72,17.58,15.16,19.85,15.61,...,11.43,29.17,18.34,21.57,17.39,18.01,21.91,30.291497,-92.411037,22001
2,Accomack County,VA,11.22,8.96,16.00,23.94,9.45,18.56,7.26,9.15,...,11.20,18.21,18.05,15.20,10.80,16.19,13.39,37.765944,-75.757807,51001
3,Ada County,ID,0.74,0.43,0.96,1.27,0.32,0.36,1.08,0.99,...,1.37,0.81,0.86,0.08,1.08,0.16,1.54,43.447861,-116.244456,16001
4,Adair County,IA,9.13,9.49,6.81,12.17,7.76,15.41,17.27,13.09,...,18.94,19.61,10.04,16.50,14.38,6.44,9.74,41.328528,-94.478164,19001

In [9]:
# Export the Precip DataFrame to a new Precip CSV file
output_csv_file = "Data/precip_data.csv"
precip_data_.to_csv(output_csv_file, index=False)

print(f"The Precipitation DataFrame has been exported to {output_csv_file}.")

The Precipitation DataFrame has been exported to Data/precip_data.csv.

In [10]:
# Export the Temp DataFrame to a new Temp CSV file
output_csv_file = "Data/temp_data.csv"
temp_data_.to_csv(output_csv_file, index=False)

print(f"The Temperature DataFrame has been exported to {output_csv_file}.")

The Temperature DataFrame has been exported to Data/temp_data.csv.

In [11]:
# Export the LD DataFrame to a new LD CSV file
output_csv_file = "Data/LD_data.csv"
LD_data_.to_csv(output_csv_file, index=False)

print(f"The LD DataFrame has been exported to {output_csv_file}.")

The LD DataFrame has been exported to Data/LD_data.csv.

In [12]:
# Export the LD DataFrame to a new LD CSV file
output_csv_file = "Data/WN_data.csv"
WN_data_.to_csv(output_csv_file, index=False)

print(f"The WN DataFrame has been exported to {output_csv_file}.")

The WN DataFrame has been exported to Data/WN_data.csv.